name: Build Wine
on:
  push:
    branches:
      - main

jobs:
  build_wine:
    environment: cachix
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: saro-wine
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build
